### ISSUE TITLE
[NEW ALGORITHM] Insert a new node after and before a given node in singly, doubly and circular linked list

### ISSUE THREAD

**Issue by Tanyajain2006** [AlgoGenesis/C#1250]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  Insert a new node after and before a given node
```[NEW ALGORITHM]```  

### About: 
Insert a new node after and before a given node in singly, doubly and circular linked list

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Tanyajain2006** [comment]
Want to insert node before/after in singly, doubly, circular singly and circular doubly linked list

**Comment by Ritika-K7** [comment]
@Tanyajain2006 @pankaj-bind 
Please assign this to me .

**Comment by Tanyajain2006** [comment]
> @Tanyajain2006 @pankaj-bind 
> Please assign this to me .

Hi Ritika,
Thank you for your offer to contribute! I really appreciate it. However, I’ve already completed this part of the project. When the project admin assigns, I just need to create a pull request.
I hope you understand, and I’ll definitely keep you in mind for future tasks!

Thanks

**Comment by Ritika-K7** [comment]
Hi @pankaj-bind 
I hope you are doing good.
I’m still getting familiar with open-source practices, so I wanted to check a few things about contributing to this repo since it’s listed with GSSoC and Hacktoberfest tags.

1.Contributor Roles: Is @Tanyajain2006 a maintainer, or just a contributor? I asked because she mentioned she’d completed a task and said not to request an assignment. I wonder if contributors can also suggest that others contributors to  hold off on requesting assignments.
2.Self-Created Issues: I noticed that some contributors and Tanya Jain are creating issues and then resolving them, tagging them with GSSoC and Hacktoberfest labels. Is this standard practice, and is it okay? It seems like an easier way to gain points, so I wanted to clarify if that’s how we’re encouraged to contribute here.
3.Assignment Process: If creating and completing issues yourself is allowed, should I go about contributing this way too, and don't wait for assignments from maintainers like you?
3.Repo Guidelines: Are there any specific guidelines for contributors, especially for tasks labeled with GSSoC and Hacktoberfest?

Thanks for helping me understand the process! Just want to make sure I'm on the right track.
with regards,
Ritika

**Comment by Tanyajain2006** [comment]
Actually I am also new to open source and still in learning phase. I am
sorry if I am not able to make you understand what I actually meant.

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
